version: '3'

services:
    nginx:
        build: requirements/nginx/
        image: nginx
        container_name: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        volumes:
            - wp_files:/home
        # networks:
        #     - backend
        restart: always

    db:
        build: requirements/mariadb
        image: mariadb
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - "/Users/clorin/42/data/mysql:/mariadb"
        # networks:
        #     - backend
    wordpress:
        build:
            context: ./requirements/wordpress
            dockerfile: Dockerfile
        image: wordpress
        depends_on:
            - db
        volumes:
            - /Users/clorin/42/data:/wordpress
        # networks:
        #     - backend
volumes:
  wp_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/wordpress'

# network:
#     - backend: