version: '3'

services:
    nginx:
        build: requirements/nginx/
        image: nginx
        container_name: nginx
        depends_on:
            - wordpress
        ports:
            - "443:443"
        volumes:
            - wp_files:/home
        # networks:
        #     - backend
        restart: always

    db:
        build: requirements/mariadb
        image: mariadb
        container_name: mariadb
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        volumes:
            - dbdata:/home/mariadb
        restart: always
        # networks:
        #     - backend
    wordpress:
        build: requirements/wordpress
        image: wordpress
        container_name: wordpress
        depends_on:
            - db
        volumes:
            - wp_files:${WORDPRESS_PATH}
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST}
            - WORDPRESS_DB_ADMIN=${WORDPRESS_DB_ADMIN}
            - WORDPRESS_DB_ADMIN_PASSWORD=${WORDPRESS_DB_ADMIN_PASSWORD}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_USER}
            - WORDPRESS_DB_USER_PASSWORD=${WORDPRESS_DB_USER_PASSWORD}
            - WORDPRESS_PATH=${WORDPRESS_PATH}
            - DOMAIN_NAME=${DOMAIN_NAME}

        restart: always
        # networks:
        #     - backend
volumes:
    wp_files:
        driver: local
        driver_opts:
            type: none
            o: 'bind'
            device: '$HOME/data/wordpress'
    dbdata:
        driver: local
        driver_opts:
            type: none
            o: 'bind'
            device: '$HOME/data/db'
# network:
#     - backend: