version: '3'
services:
  app:
    build: .
    image: flask-redis:1.0
    container_name: flask
    environment:
      - FLASK_ENV=development
    ports:
      - 80:80
    networks:
      - backend
    volumes:
      - dbdata:/database
  redis:
    image: redis:4.0.11-alpine
    container_name: redis
    networks:
      - backend
    volumes:
      - dbdata:/data

networks:
  backend:

volumes:
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/clorin/goinfre/data'