version: '3.3'

services:
   nginx:
     container_name: nginx
     image: nginx:alpine
     ports:
     - 8085:80
     depends_on:
      - wordpress-fpm
     volumes:
       - ./conf.d:/etc/nginx/conf.d
       - wp_files:/var/www/html
     links:
        - wordpress-fpm 
   db:
     image: mariadb:10
     container_name: mariadb
     environment:
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
       MYSQL_DATABASE: "${MYSQL_DATABASE}"
       MYSQL_USER: "${MYSQL_USER}"
       MYSQL_PASSWORD: "${MYSQL_PASSWORD}"

   wordpress-fpm:
     image: wordpress:5-fpm-alpine
     container_name: wordpress
     links:
      - db
     volumes:
      - wp_files:/var/www/html
     environment:
       WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
       WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
       WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
       WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"
volumes:
  wp_files:
