version: '3.5'

services:
   nginx:
     container_name: nginx
     # build:
     #        context: ./nginx
     #        dockerfile: Dockerfile
     image: nginx:stable
     ports:
     # - 443:443
     - 8085:80
     depends_on:
      - wordpress-fpm
     volumes:
       - ./conf.d:/etc/nginx/conf.d
       - wp_files:/var/www/html
     # links:
     #    - wordpress-fpm
     networks:
      - frontend
   db:
     image: mariadb:10
     container_name: mariadb
     environment:
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
       MYSQL_DATABASE: "${MYSQL_DATABASE}"
       MYSQL_USER: "${MYSQL_USER}"
       MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
     volumes:
      - dbdata:/var/lib/mysql
     networks:
      - backend

   wordpress-fpm:
     image: wordpress:5-fpm
     container_name: wordpress
     # links:
     #  - db
     networks:
      - frontend
      - backend
     volumes:
      - wp_files:/var/www/html
     environment:
       WORDPRESS_DB_HOST: "${WORDPRESS_DB_HOST}"
       WORDPRESS_DB_NAME: "${WORDPRESS_DB_NAME}"
       WORDPRESS_DB_USER: "${WORDPRESS_DB_USER}"
       WORDPRESS_DB_PASSWORD: "${WORDPRESS_DB_PASSWORD}"

volumes:
  wp_files:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/wordpress'
  dbdata:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '$HOME/data/db'

networks:
  frontend:
  backend:
